### ISSUE TITLE
demo.m evaluate.m

### ISSUE THREAD

**Issue by renxiaosa00** [CVIR-Lab/MarsData#1]
There are no file “demo.m evaluate.m”

**Comment by XueMingXiao** [comment]
sorry for that, we have uploaded the "demo.m" file. For the file "evaluate.m", we uploaded "*.m" files of all the metrics in the file "Evaluation", such as "Fmeasure.m", "MAE2.m" and "CallAUCScore.m". You can check the model by any evaluate function in the file "Evaluation". Based on such consideration, we do not write and upload the "evaluate.m" file. Hope this helps.
