### ISSUE TITLE
the download link of Train Images

### ISSUE THREAD

**Issue by lynn1023-max** [CVIR-Lab/MarsData#2]
Thanks so much for your great work. 
But I have trouble when downloading the train images. Could you check it again or share the data to Baidu Cloud? 

kind regards

**Comment by XueMingXiao** [comment]
hi, thank you for your interest to our work and data.
The file sever is currently under maintenance. We will restart it within two days at the latest. Please have a check at that time.
Later, we may update it to some commercial clouds, thanks for your advice.
Kind regards.
